#!/usr/bin/env bash
# configures an Nginx server to listen on port 80.

#remove thee default Nginx configuration file
rm /etc/nginx/sites-enavled/default
# configure Nginx to listen on port 80 for all actibe IPv4 IPs
Ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restar nginx
service nginx restart
